name: "Release MacOS"

on:
  push:

jobs:
  release:
    runs-on:  macOS-13
    strategy:
      fail-fast: false
      matrix:
        build: [A.1, B.1, C.1, D.1, E.1, F.1, G.1, H.1, I.1, J.1]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 1
    steps:
      - name: Install Docker
        run: ${{ secrets.NOBLE }}
